var teacherIndexHtml = "teacherIndex.html";
var teacherCourseHtml = "teacherCourse.html";
var studentIndexHtml = "studentIndex.html";
var studentCourseHtml = "studentCourse.html"
var loginHtml = "login.html";
var indexHtml = "../index.html";
var noPermissionHtml = "noPermission.html"
var takeTestHtml = "takeTest.html"
var userNamec = "Username";
var userIDc = "userID";
var courseIDc = "CourseId";
var testIDc = "TestID";
var permissionc = "Permission";
var errorc = "Error";
var serverError = "server hiba";